
version: "3.8"

services:
  node:
    image: daloflow:v2
    volumes:
      - type: bind
        source: /home/acaldero/work/daloflow
        target: /daloflow
    runtime: nvidia
    networks:
      - backend

networks:
  backend:
    ipam:
      config:
        - subnet: 192.168.0.0/16

