
version: "3.8"

services:
  node:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: daloflow:v2
    volumes:
      - type: bind
        source: /mnt/local-storage/daloflow
        target: /usr/src/daloflow

